/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cocourse.server.gui;

import cocourse.server.Server;

import javax.swing.*;
import java.text.SimpleDateFormat;

/**
 * @author decanter
 */
public class ServerGUI extends javax.swing.JFrame {

	private long startTime;
	private long endTime;
	private Server server;
	private Timer timer;
	private int logline = 0;

	/**
	 * Creates new form serverfront
	 */
	public ServerGUI( ) {

		startTime = System.currentTimeMillis( );
		endTime = System.currentTimeMillis( ) + 5000L;

		if ( server == null ) {
			System.out.println( "a" );
			NewServerGUI d = new NewServerGUI( this , true , this.server );
			d.setVisible( true );
			server = d.getServer( );
		}

		timer = new javax.swing.Timer( 100 , e -> {
			while ( logline < server.getLog( ).size( ) ) {
				txtLog.append( server.getLog( ).get( logline ).toString( ) + "\n" );
				logline++;
			}
			this.txtTime.setText(
					new SimpleDateFormat( "hh:mm:ss" ).format( System.currentTimeMillis( ) ) );
			this.txtTimeLeft.setText(
					new SimpleDateFormat( "hh:mm:ss" ).format( System.currentTimeMillis( ) ) );
		} );


		timer.start( );

		initComponents( );

		this.txtIp.setText( server.getIp( ).toString( ) );

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents( ) {

		jPanel2 = new javax.swing.JPanel( );
		jScrollPane1 = new javax.swing.JScrollPane( );
		txtLog = new javax.swing.JTextArea( );
		lblHighestBid = new javax.swing.JLabel( );
		txtHighestBid = new javax.swing.JTextField( );
		lblHighestBidder = new javax.swing.JLabel( );
		txtHighestBidder = new javax.swing.JTextField( );
		txtTimeLeft = new javax.swing.JTextField( );
		lblTimeLeft = new javax.swing.JLabel( );
		lblLog = new javax.swing.JLabel( );
		jScrollPane2 = new javax.swing.JScrollPane( );
		txtUsers = new javax.swing.JTextArea( );
		lblUsers = new javax.swing.JLabel( );
		jSeparator1 = new javax.swing.JSeparator( );
		lblIp = new javax.swing.JLabel( );
		txtIp = new javax.swing.JTextField( );
		txtTime = new javax.swing.JTextField( );
		jLabel1 = new javax.swing.JLabel( );
		jMenuBar1 = new javax.swing.JMenuBar( );
		jMenu1 = new javax.swing.JMenu( );
		jMenu2 = new javax.swing.JMenu( );

		setDefaultCloseOperation( javax.swing.WindowConstants.EXIT_ON_CLOSE );

		txtLog.setColumns( 20 );
		txtLog.setRows( 5 );
		jScrollPane1.setViewportView( txtLog );

		lblHighestBid.setText( "highest bid" );

		lblHighestBidder.setText( "higest bidder" );

		lblTimeLeft.setText( "time left" );

		lblLog.setText( "log" );

		jScrollPane2.setHorizontalScrollBarPolicy( javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER );

		txtUsers.setEditable( false );
		txtUsers.setColumns( 20 );
		txtUsers.setRows( 4 );
		txtUsers.setTabSize( 1 );
		jScrollPane2.setViewportView( txtUsers );

		lblUsers.setText( "users" );
		lblUsers.setVerticalAlignment( javax.swing.SwingConstants.TOP );

		lblIp.setText( "ip address" );

		txtIp.setEditable( false );

		txtTime.setEditable( false );

		jLabel1.setText( "Current Time" );

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout( jPanel2 );
		jPanel2.setLayout( jPanel2Layout );
		jPanel2Layout.setHorizontalGroup(
				jPanel2Layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
						.addGroup( jPanel2Layout.createSequentialGroup( )
								.addContainerGap( )
								.addGroup( jPanel2Layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING , false )
										.addGroup( javax.swing.GroupLayout.Alignment.TRAILING , jPanel2Layout.createSequentialGroup( )
												.addComponent( lblIp )
												.addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED )
												.addComponent( txtIp , javax.swing.GroupLayout.PREFERRED_SIZE , 140 , javax.swing.GroupLayout.PREFERRED_SIZE )
												.addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED , 148 , Short.MAX_VALUE )
												.addComponent( jLabel1 )
												.addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED )
												.addComponent( txtTime , javax.swing.GroupLayout.PREFERRED_SIZE , 79 , javax.swing.GroupLayout.PREFERRED_SIZE ) )
										.addComponent( jScrollPane1 , javax.swing.GroupLayout.Alignment.TRAILING )
										.addComponent( jSeparator1 , javax.swing.GroupLayout.Alignment.TRAILING )
										.addGroup( jPanel2Layout.createSequentialGroup( )
												.addGroup( jPanel2Layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
														.addGroup( jPanel2Layout.createSequentialGroup( )
																.addComponent( lblLog )
																.addGap( 322 , 322 , 322 ) )
														.addGroup( javax.swing.GroupLayout.Alignment.TRAILING , jPanel2Layout
																.createSequentialGroup( )
																.addGroup( jPanel2Layout
																		.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
																		.addComponent( lblHighestBid )
																		.addComponent( lblHighestBidder )
																		.addComponent( lblTimeLeft ) )
																.addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.UNRELATED )
																.addGroup( jPanel2Layout
																		.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING , false )
																		.addComponent( txtHighestBid )
																		.addComponent( txtHighestBidder , javax.swing.GroupLayout.DEFAULT_SIZE , 184 , Short.MAX_VALUE )
																		.addComponent( txtTimeLeft ) )
																.addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED )
																.addComponent( lblUsers ) ) )
												.addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED )
												.addComponent( jScrollPane2 , javax.swing.GroupLayout.PREFERRED_SIZE , 0 , Short.MAX_VALUE ) ) )
								.addContainerGap( javax.swing.GroupLayout.DEFAULT_SIZE , Short.MAX_VALUE ) )
		);
		jPanel2Layout.setVerticalGroup(
				jPanel2Layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
						.addGroup( javax.swing.GroupLayout.Alignment.TRAILING , jPanel2Layout.createSequentialGroup( )
								.addContainerGap( )
								.addGroup( jPanel2Layout.createParallelGroup( javax.swing.GroupLayout.Alignment.BASELINE )
										.addComponent( lblIp )
										.addComponent( txtIp , javax.swing.GroupLayout.PREFERRED_SIZE , javax.swing.GroupLayout.DEFAULT_SIZE , javax.swing.GroupLayout.PREFERRED_SIZE )
										.addComponent( txtTime , javax.swing.GroupLayout.PREFERRED_SIZE , javax.swing.GroupLayout.DEFAULT_SIZE , javax.swing.GroupLayout.PREFERRED_SIZE )
										.addComponent( jLabel1 ) )
								.addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED )
								.addComponent( jSeparator1 , javax.swing.GroupLayout.PREFERRED_SIZE , 10 , javax.swing.GroupLayout.PREFERRED_SIZE )
								.addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED )
								.addGroup( jPanel2Layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
										.addGroup( jPanel2Layout.createSequentialGroup( )
												.addGap( 0 , 0 , Short.MAX_VALUE )
												.addGroup( jPanel2Layout.createParallelGroup( javax.swing.GroupLayout.Alignment.BASELINE )
														.addComponent( txtTimeLeft , javax.swing.GroupLayout.PREFERRED_SIZE , javax.swing.GroupLayout.DEFAULT_SIZE , javax.swing.GroupLayout.PREFERRED_SIZE )
														.addComponent( lblTimeLeft ) )
												.addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED )
												.addGroup( jPanel2Layout.createParallelGroup( javax.swing.GroupLayout.Alignment.BASELINE )
														.addComponent( lblHighestBid )
														.addComponent( txtHighestBid , javax.swing.GroupLayout.PREFERRED_SIZE , javax.swing.GroupLayout.DEFAULT_SIZE , javax.swing.GroupLayout.PREFERRED_SIZE ) )
												.addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED )
												.addGroup( jPanel2Layout.createParallelGroup( javax.swing.GroupLayout.Alignment.BASELINE )
														.addComponent( lblHighestBidder )
														.addComponent( txtHighestBidder , javax.swing.GroupLayout.PREFERRED_SIZE , javax.swing.GroupLayout.DEFAULT_SIZE , javax.swing.GroupLayout.PREFERRED_SIZE ) )
												.addGap( 21 , 21 , 21 )
												.addComponent( lblLog ) )
										.addGroup( jPanel2Layout.createSequentialGroup( )
												.addGroup( jPanel2Layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
														.addComponent( lblUsers )
														.addComponent( jScrollPane2 , javax.swing.GroupLayout.PREFERRED_SIZE , 107 , javax.swing.GroupLayout.PREFERRED_SIZE ) )
												.addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED , javax.swing.GroupLayout.DEFAULT_SIZE , Short.MAX_VALUE ) ) )
								.addComponent( jScrollPane1 , javax.swing.GroupLayout.PREFERRED_SIZE , 212 , javax.swing.GroupLayout.PREFERRED_SIZE )
								.addContainerGap( ) )
		);

		jMenu1.setText( "File" );
		jMenuBar1.add( jMenu1 );

		jMenu2.setText( "Edit" );
		jMenuBar1.add( jMenu2 );

		setJMenuBar( jMenuBar1 );

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout( getContentPane( ) );
		getContentPane( ).setLayout( layout );
		layout.setHorizontalGroup(
				layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
						.addGroup( layout.createSequentialGroup( )
								.addContainerGap( javax.swing.GroupLayout.DEFAULT_SIZE , Short.MAX_VALUE )
								.addComponent( jPanel2 , javax.swing.GroupLayout.PREFERRED_SIZE , javax.swing.GroupLayout.DEFAULT_SIZE , javax.swing.GroupLayout.PREFERRED_SIZE ) )
		);
		layout.setVerticalGroup(
				layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
						.addGroup( layout.createSequentialGroup( )
								.addContainerGap( javax.swing.GroupLayout.DEFAULT_SIZE , Short.MAX_VALUE )
								.addComponent( jPanel2 , javax.swing.GroupLayout.PREFERRED_SIZE , javax.swing.GroupLayout.DEFAULT_SIZE , javax.swing.GroupLayout.PREFERRED_SIZE ) )
		);

		pack( );
	}// </editor-fold>//GEN-END:initComponents


	/**
	 * @param args the command line arguments
	 */
	public static void main( String args[] ) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels( ) ) {
				if ( "Nimbus".equals( info.getName( ) ) ) {
					javax.swing.UIManager.setLookAndFeel( info.getClassName( ) );
					break;
				}
			}
		} catch ( ClassNotFoundException ex ) {
			java.util.logging.Logger.getLogger( ServerGUI.class.getName( ) )
					.log( java.util.logging.Level.SEVERE , null , ex );
		} catch ( InstantiationException ex ) {
			java.util.logging.Logger.getLogger( ServerGUI.class.getName( ) )
					.log( java.util.logging.Level.SEVERE , null , ex );
		} catch ( IllegalAccessException ex ) {
			java.util.logging.Logger.getLogger( ServerGUI.class.getName( ) )
					.log( java.util.logging.Level.SEVERE , null , ex );
		} catch ( javax.swing.UnsupportedLookAndFeelException ex ) {
			java.util.logging.Logger.getLogger( ServerGUI.class.getName( ) )
					.log( java.util.logging.Level.SEVERE , null , ex );
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater( ( ) -> new ServerGUI( ).setVisible( true ) );

	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel jLabel1;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JLabel lblHighestBid;
	private javax.swing.JLabel lblHighestBidder;
	private javax.swing.JLabel lblIp;
	private javax.swing.JLabel lblLog;
	private javax.swing.JLabel lblTimeLeft;
	private javax.swing.JLabel lblUsers;
	private javax.swing.JTextField txtHighestBid;
	private javax.swing.JTextField txtHighestBidder;
	private javax.swing.JTextField txtIp;
	private javax.swing.JTextArea txtLog;
	private javax.swing.JTextField txtTime;
	private javax.swing.JTextField txtTimeLeft;
	private javax.swing.JTextArea txtUsers;
	// End of variables declaration//GEN-END:variables
}
